# Generated by Django 4.1.7 on 2024-10-26 18:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="say something about yourself", verbose_name="about me"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+880-1923675361",
                max_length=30,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
